name: 'Build frontend'
author: 'IhateTrains'
branding:
  icon: 'layout'
  color: 'orange'
description: Build frontend for a ParadoxGameConverters converter
inputs:
  fronter_dir:
    description: Path to Fronter.NET submodule
    required: true
  release_dir:
    description: Path to converter's root release directory
    required: true
  build_ConverterFrontend:
    description: Whether to build ConverterFrontend
    default: true
  self_contained:
    description: Whether to include .NET runtime in the ConverterFrontend executable.
    default: true
  build_updater:
    description: Whether to build updater
    default: true
runs:
  using: composite
  steps:
    - shell: bash
      env:
        FRONTER_DIR: ${{ inputs.fronter_dir }}
        RELEASE_DIR: ${{ inputs.release_dir }}
        BUILD_CONVERTERFRONTEND: ${{ inputs.build_ConverterFrontend }}
        SELF_CONTAINED: ${{ inputs.self_contained }}
        BUILD_UPDATER: ${{ inputs.build_updater }}
      run: |
        read script_path < <(echo "${{ github.action_path }}/entrypoint.sh" | sed 's.\\./.g')
        bash $script_path