name: Build

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [[self-hosted, linux], macos-13, [self-hosted, windows]]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: "Setup Dotnet for use with actions"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'preview'
    - name: "Build"
      working-directory: Fronter.NET
      run: |
       dotnet build
