name: Build

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: "Setup Dotnet for use with actions"
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '6.x'
    - name: "Build"
      uses: ./.github/actions/build_frontend
      with:
        fronter_dir: '.'
        release_dir: 'Release'
