name: Build

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [[self-hosted, linux], [self-hosted, windows], macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: "Setup Dotnet for use with actions"
      # don't run on self-hosted Windows
      if: ${{ !contains(toJSON(matrix.os), 'windows') || !contains(toJSON(matrix.os), 'self-hosted') }}
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: "Build"
      uses: ./.github/actions/build_frontend
      with:
        fronter_dir: .
        release_dir: Publish
        build_ConverterFrontend: true
        self_contained: true
        build_updater: true
